#!/usr/bin/env bash
# Listing processes
# Requirements:
#	-Must show all processes, for all users, including those which might not have a TTY
#	-Display in a user-oriented format
#	-Show process hierarchy

ps -faux
